### ISSUE TITLE
Adding Inline Support

### ISSUE THREAD

**Issue by rhnvrm** [FlameFractal/SNU-Mess-Menu-Notifs#4]
https://core.telegram.org/bots/inline Might be a nice feature to add

**Comment by FlameFractal** [comment]
Considering that barely 10 people are using it rn, have no motivation to spend time on inline! 😝

**Comment by FlameFractal** [comment]
added in version  v2.0.0 with commit 5065a4b

**Comment by rhnvrm** [comment]
Great
